// lib/firebase_options.dart

// File generated by FlutterFire CLI.
//
// TODO: Este arquivo foi gerado manualmente para corrigir um problema de deploy na web.
// Se você rodar `flutterfire configure` novamente, verifique se ele não reintroduz o `dotenv`.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqx14PzCc1euMk2v4Ou-_FWdz7GV891Hk',
    appId: '1:225819514315:web:07f01edca7c35aef23d24e',
    messagingSenderId: '225819514315',
    projectId: 'resumo-livros',
    authDomain: 'resumo-livros.firebaseapp.com',
    storageBucket: 'resumo-livros.appspot.com',
    measurementId: 'G-TK6LBXB0DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcuHVPneHpt5LWM3u2ZtpUimfHrQsNAlk',
    appId: '1:225819514315:android:e15bf8d871ceaffe23d24e',
    messagingSenderId: '225819514315',
    projectId: 'resumo-livros',
    storageBucket: 'resumo-livros.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_LJPJTuivsaq2ZVFFgcUo0UA6vPElHl0',
    appId: '1:225819514315:ios:cb9ebdb3a463ebcd23d24e',
    messagingSenderId: '225819514315',
    projectId: 'resumo-livros',
    storageBucket: 'resumo-livros.appspot.com',
    iosBundleId: 'com.example.resumoDosDeusesFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_LJPJTuivsaq2ZVFFgcUo0UA6vPElHl0',
    appId: '1:225819514315:ios:cb9ebdb3a463ebcd23d24e',
    messagingSenderId: '225819514315',
    projectId: 'resumo-livros',
    storageBucket: 'resumo-livros.appspot.com',
    iosBundleId: 'com.example.resumoDosDeusesFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqx14PzCc1euMk2v4Ou-_FWdz7GV891Hk',
    appId: '1:225819514315:web:0fb1d329c9ffe4df23d24e',
    messagingSenderId: '225819514315',
    projectId: 'resumo-livros',
    authDomain: 'resumo-livros.firebaseapp.com',
    storageBucket: 'resumo-livros.appspot.com',
    measurementId: 'G-QLPDQKNJCW',
  );
}
